# Introduction


## Overview

-   Forecast pre-July-law PMT wage tax as a function of wages - quarterly then convert to monthly

    - Develop separate wage forecasts for NYC and suburban counties, based on (1) review of available forecasts and (2) time-series approaches
    
    -   Convert the quarterly wage forecasts into monthly based on historical patterns
    
    -   Split the monthly wage tax into NYC and suburban components, based on splits in the quarterly wage data
    
-   Forecast monthly July+ PMT wage tax by estimating the additional NYC tax

    -   Start with monthly NYC wage tax estimates from above
    
    -   Estimate increase in NYC, allowing for some slippage in July
    
    
    
    


## Steps

-   Get and clean historical PMT and related data

-   Get and clean economic data

-   Examine recent trends

-   Forecast revenue

## Appendices

-   PMT law

-   What's the lag between collections by Tax and receipt by MTA?

    -   Payroll tax -- 1 month assumption for now
    
    -   Self employment net earnings tax

-   2023 changes

## Notes

-   PMT projections CY 2023 and 2024

-   New rates July 1

-   DOB estimate for first-year impact of the 2023 changes was ~$460m, KW believes

-   Full-year impact was estimated at ~$1.1 billion

-   MMTOA the corp surcharge rate was fixed at 30%, no longer potentially adjusted by Tax Department [verify]
